# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
