# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
